version: '3.4'

services:
  projectx.httpapi.host:
    image: webadmin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - projectxhttpapihost
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json